In [4]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# AND gate 입력과 출력
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 0, 0, 1])  # AND gate 결과

# 모델 생성 및 학습
model = LogisticRegression()
model.fit(X, y)

# 예측
predictions = model.predict(X)
print("입력 X:")
print(X)
print("예측 결과:")
print(predictions)

# 실제 값과 비교
print("정답과 일치 여부:", predictions == y)


입력 X:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
예측 결과:
[0 0 0 0]
정답과 일치 여부: [ True  True  True False]


In [5]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# XOR gate 입력과 출력
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 1, 1, 0])  # XOR 결과

# 모델 생성 및 학습
model = LogisticRegression()
model.fit(X, y)

# 예측
predictions = model.predict(X)
print("입력 X:")
print(X)
print("예측 결과:")
print(predictions)

# 실제 값과 비교
print("정답과 일치 여부:", predictions == y)


입력 X:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
예측 결과:
[0 0 0 0]
정답과 일치 여부: [ True False False  True]


In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import numpy as np

# XOR 데이터
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 1, 1, 0])

# 다항 특성 추가 + 로지스틱 회귀 파이프라인
model = make_pipeline(PolynomialFeatures(degree=2), LogisticRegression())
model.fit(X, y)

# 예측
predictions = model.predict(X)
print("예측 결과:", predictions)
print("정답과 일치 여부:", predictions == y)


예측 결과: [1 1 1 0]
정답과 일치 여부: [False  True  True  True]


In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import numpy as np

# XOR gate 입력과 출력
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 1, 1, 0])

# 다항 특성 추가 후 로지스틱 회귀 (solver 설정 필수)
model = make_pipeline(
    PolynomialFeatures(degree=2, include_bias=False),
    LogisticRegression(solver='lbfgs', max_iter=1000)
)

model.fit(X, y)

# 예측
predictions = model.predict(X)
print("예측 결과:", predictions)
print("정답과 일치 여부:", predictions == y)


예측 결과: [1 1 1 0]
정답과 일치 여부: [False  True  True  True]
